### ISSUE TITLE
[IOS] AIRSDK 33.0.288  Error #1014: Class flash.text::StageText could not be found.

### ISSUE THREAD

**Issue by truongnx9218** [Gamua/Adobe-Runtime-Support#156]
## Problem Description
[Fault] exception, information=VerifyError: Error #1014: Class flash.text::StageText could not be found.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at flash.tools.debugger.concrete.DManager.getFrame(DManager.java:921)
	at flash.tools.debugger.concrete.PlayerSession.pullUpActivationObjectVariables(PlayerSession.java:1113)
	at flash.tools.debugger.concrete.PlayerSession.requestFrame(PlayerSession.java:1089)
	at flash.tools.debugger.concrete.PlayerSession.getValueWorker(PlayerSession.java:1211)
	at flash.tools.debugger.concrete.IsolatePlayerSession.getValue(IsolatePlayerSession.java:123)
	at flex.tools.debugger.cli.ExpressionContext.memberNamed(ExpressionContext.java:438)
	at flex.tools.debugger.cli.ExpressionContext.locateParentForNamed(ExpressionContext.java:540)
	at flex.tools.debugger.cli.ExpressionContext.determineContext(ExpressionContext.java:490)
	at flex.tools.debugger.cli.ExpressionContext.resolveToVariable(ExpressionContext.java:350)
	at flex.tools.debugger.cli.ExpressionContext.lookup(ExpressionContext.java:169)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:161)
	at macromedia.asc.parser.ThisExpressionNode.evaluate(ThisExpressionNode.java:34)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:1031)
	at macromedia.asc.parser.ListNode.evaluate(ListNode.java:44)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:1031)
	at macromedia.asc.parser.ListNode.evaluate(ListNode.java:44)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:1065)
	at macromedia.asc.parser.ExpressionStatementNode.evaluate(ExpressionStatementNode.java:50)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:1306)
	at macromedia.asc.parser.ProgramNode.evaluate(ProgramNode.java:80)
	at flash.tools.debugger.expression.DebuggerExpression.evaluate(DebuggerExpression.java:106)
	at flex.tools.debugger.cli.ExpressionCache.evaluate(ExpressionCache.java:101)
	at flex.tools.debugger.cli.DebugCLI.evalExpression(DebugCLI.java:4023)
	at flex.tools.debugger.cli.DebugCLI.evalExpression(DebugCLI.java:4015)
	at flex.tools.debugger.cli.DebugCLI.doPrint(DebugCLI.java:3941)
	at flex.tools.debugger.cli.DebugCLI.processLine(DebugCLI.java:7032)
	at flex.tools.debugger.cli.DebugCLI.process(DebugCLI.java:828)
	at flex.tools.debugger.cli.DebugCLI.execute(DebugCLI.java:669)
	at flex.tools.debugger.cli.DebugCLI.main(DebugCLI.java:461)
* Which AIR SDK did you use?  
    SDK 33.0.288 - SDK 33.0.315
* Describe the affected environment: 
   IOS 13 - IPhone 6s/ IphoneX

**Comment by ajwfrost** [comment]
@truongnx9218 I believe this issue was likely caused by an invalid namespace in the descriptor file, are you able to check this please? Namespace should be 32.0, or if you're using the very latest version (just released today) then you can use 33.1. But 33.0 isn't valid I'm afraid..
