### ISSUE TITLE
Air 33 debug with error "flash.external::ExtensionContext could not be found." in macos catalina

### ISSUE THREAD

**Issue by AdamSun** [Gamua/Adobe-Runtime-Support#164]
## Air 33 debug with error "flash.external::ExtensionContext could not be found." in macos catalina
pls help! I get mad when i want to add the apple sign in service to our app.I have to upgrade the macos and xcode and use air 33.Finally I get a problem that i can not resolve, pls help, thanks!
* Which AIR SDK did you use? 
AIR SDK 33.0.2.330

* Describe the affected environment:
AIR iOS

* macOS Version: 
catalina 10.15.1

* develop tool:
Intellij Idea

## Steps to Reproduce

* when the ipa is created and debug it with Air 33, the error will occur, this project contain an ane, it works fine before upgrade the macos and air 33.the error message is:
```
[Fault] exception, information=VerifyError: Error #1014: Class flash.external::ExtensionContext could not be found.
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at flash.tools.debugger.concrete.DManager.getFrame(DManager.java:921)
	at flash.tools.debugger.concrete.PlayerSession.pullUpActivationObjectVariables(PlayerSession.java:1113)
	at flash.tools.debugger.concrete.PlayerSession.requestFrame(PlayerSession.java:1089)
	at flash.tools.debugger.concrete.PlayerSession.getValueWorker(PlayerSession.java:1211)
	at flash.tools.debugger.concrete.IsolatePlayerSession.getValue(IsolatePlayerSession.java:123)
	at flex.tools.debugger.cli.ExpressionContext.memberNamed(ExpressionContext.java:438)
	at flex.tools.debugger.cli.ExpressionContext.locateParentForNamed(ExpressionContext.java:540)
	at flex.tools.debugger.cli.ExpressionContext.determineContext(ExpressionContext.java:490)
	at flex.tools.debugger.cli.ExpressionContext.resolveToVariable(ExpressionContext.java:350)
	at flex.tools.debugger.cli.ExpressionContext.lookup(ExpressionContext.java:169)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:161)
	at macromedia.asc.parser.ThisExpressionNode.evaluate(ThisExpressionNode.java:34)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:1031)
	at macromedia.asc.parser.ListNode.evaluate(ListNode.java:44)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:1031)
	at macromedia.asc.parser.ListNode.evaluate(ListNode.java:44)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:1065)
	at macromedia.asc.parser.ExpressionStatementNode.evaluate(ExpressionStatementNode.java:50)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:1306)
	at macromedia.asc.parser.ProgramNode.evaluate(ProgramNode.java:80)
	at flash.tools.debugger.expression.DebuggerExpression.evaluate(DebuggerExpression.java:106)
	at flex.tools.debugger.cli.ExpressionCache.evaluate(ExpressionCache.java:101)
	at flex.tools.debugger.cli.DebugCLI.evalExpression(DebugCLI.java:4023)
	at flex.tools.debugger.cli.DebugCLI.evalExpression(DebugCLI.java:4015)
	at flex.tools.debugger.cli.DebugCLI.doPrint(DebugCLI.java:3941)
	at flex.tools.debugger.cli.DebugCLI.processLine(DebugCLI.java:7032)
	at flex.tools.debugger.cli.DebugCLI.process(DebugCLI.java:828)
	at flex.tools.debugger.cli.DebugCLI.execute(DebugCLI.java:669)
	at flex.tools.debugger.cli.DebugCLI.main(DebugCLI.java:461)
```

**Comment by CodingFishWu** [comment]
I have encountered the same issue. Does anyone has any suggestions?

**Comment by MESepehr** [comment]
And also same problem when you add flash.system.Worker or flash.text.StageText to the SWF and compile with Air33

**Comment by tuarua** [comment]
Try setting the namespace to 32.0 in your app.xml
although you are using SDK 33, the namespace hasn't been updated yet!

`<application xmlns="http://ns.adobe.com/air/application/32.0">`

**Comment by hcsuk** [comment]
@AdamSun  can I check whether you've tried this with the namespace 32.0. I hadn't realised that trying to use namespace 33.0 would even load, but it does seem to end up with these verifyerrors being raised.. we had to keep the namespace to 32.0 until we started distributing new builds of the desktop software (ADL + runtimes that it uses) otherwise these would be throwing errors too.

thanks
