### ISSUE TITLE
PKCS11 (eToken) signing throws an exception

### ISSUE THREAD

**Issue by gene-pavlovsky** [Gamua/Adobe-Runtime-Support#295]
## Problem Description

OS: Windows 10 x64
SDK: Harman AIR 33.1.1.98
App Target: Desktop
Java JDK: Tried Java 8 64-bit, Java 8 32-bit, Java 7 32-bit (all latest versions from Oracle)

I have an issue with adt signing using a SunPKCS11-eToken (USB hardware token with an EV Code Signing certificate from DigiCert).

I have configured the Java JDK to use the eToken (according to documentation from DigiCert).
This configuration seems to work - I can list the certificate with keytool, and I could successfully sign a test .jar file with jarsigner.

I am also able to check the certificate's password using adt:
# adt -checkstore -storetype PKCS11 -providerName SunPKCS11-eToken -storepass ""
valid password

However, signing the app fails:
# adt -package -tsa http://timestamp.digicert.com -storetype PKCS11 -storepass "" -providerName SunPKCS11-eToken -target bundle "dist/app" application.xml -C bin .
unexpected failure: Unable to create signature.
java.io.IOException: Unable to create signature.
        at com.adobe.ucf.UCFOutputStream.finalizeSig(UCFOutputStream.java:334)
        at com.adobe.air.AIROutputStream.finalizeSig(AIROutputStream.java:157)
        at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java:256)
        at com.adobe.air.nai.NativePackager.createPackage(NativePackager.java:99)
        at com.adobe.air.ADT.parseArgsAndGo(ADT.java:673)
        at com.adobe.air.ADT.run(ADT.java:471)
        at com.adobe.air.ADT.main(ADT.java:521)

The password prompt pops up, I enter the password, then adt does something for a while, then it spits out this exception. This used to work in 2017 (when I signed the previous build of this application), using Flex 4.6.0+AIR 25.0 and the same USB token (different certificate, also from DigiCert). The app received rather minor changes since then, one of them was an AIR 28.0 update. I tried adt from AIR 32.0 and Harman's AIR 33.1.1.98, with the same result.
The most annoying thing is that there are no specifics which could help identify the reason for this problem. The error message is very generic and there is no verbose/debug mode, as far as I see. Perhaps if there was a debugging option (or version) of adt, that would pinpoint what exactly is failing there?

**Comment by zwetan** [comment]
my guess is that the issue is created by using an empty storepass
`-storepass ""`

you would need to export the cert and reimport it with a not empty password
see for ex [Keystore without a password](https://blog.jdriven.com/2015/10/keystore-without-a-password/)

**Comment by gene-pavlovsky** [comment]
@zwetan The cert is on a hardware token (eToken) and is protected with a password. In fact, the EV Code Signing certificate can't be exported from the token (only the public key can be exported), and it must have a password. The `-storepass ""` option results in a password prompt of SafeNet Authentication Client (the software provided by the eToken manufacturer - Gemalto) to appear. I entered the correct password (copy-paste from KeePassXC) and then a few seconds later the exception appeared. Note: In 2017 this was working fine, using the same eToken (different cert, of course, the old one expired) and the same commands and options used for signing. Note also that keytool and jarsigner both work fine - these are Java JDK's tools, I assume they use the same Java APIs as adt does. But it seems that adt is doing something extra which makes it fail.

**Comment by zwetan** [comment]
> In 2017 this was working fine

since then Java changed how they tolerate empty storepass

eg. if before you could get away with a `-storepass ""`, you can't do that anymore

> that keytool and jarsigner both work fine

first paragraph of the link provided before
eg.
> Both the JVM and keytool have problems dealing with keystores without a password. If you try to get a listing of the keystore it will think you didn't provide a password and output falsehoods

so yeah hardware key can be a bit more fiddly to deal with, but my point is: just replace the empty password with a non empty password

either that or downgrade your java version to the point some java version x.y accept empty storepass, I don't know which version

**Comment by gene-pavlovsky** [comment]
Per your suggestion, I've just tried the same command without `-storepass ""`.

That is: ```adt -package -tsa http://timestamp.digicert.com -storetype PKCS11 -providerName SunPKCS11-eToken -target bundle "dist/MyApp-store" application.xml -C bin .```

I was asked the password in the terminal (rather than with SafeNet Authentication Client's GUI prompt, like before), and then a couple seconds later received the same error:
```
password:
unexpected failure: Unable to create signature.
java.io.IOException: Unable to create signature.
        at com.adobe.ucf.UCFOutputStream.finalizeSig(UCFOutputStream.java:334)
        at com.adobe.air.AIROutputStream.finalizeSig(AIROutputStream.java:157)
```

**Comment by gene-pavlovsky** [comment]
I've also tried a rather old java - JDK 1.7.0_80 (<2015) and it gives exactly the same error

**Comment by gene-pavlovsky** [comment]
By the way, I've got a suggestion from another developer, and having tried it out, this is a workaround for the issue. Apparently, once you have the SafeNet Authentication Client installed and the USB token plugged in, the key is also visible via some Windows-specific API.

Using `keytool -list -storetype Windows-MY`, I saw the desired certificate's private key listed.

For signing, here's the command that worked (details edited out for client's privacy): `adt -package -tsa http://timestamp.digicert.com -storetype Windows-MY -storepass "" -alias "Example Company LLC" -target bundle "dist/ExampleApp" application.xml -C bin .`
Note: if `-storepass ""` is omitted, adt asks for a password on the command line, and then SafeNet's GUI password prompts shows up. With `-storepass ""`, only SafeNet's GUI prompt shows up, and signing finished without error. And, I've confirmed this works fine with the very recent Java JDK 1.8.0_241.

I think I'll continue to use this solution, since it is easy to use and doesn't need to edit Java's security config file and configuring a eToken.cfg.

Of course, it would still be nice if the issue can be fixed, but since there is a workaround...

**Comment by zwetan** [comment]
> Per your suggestion, I've just tried the same command without -storepass "".

my suggestion was to use a non-empty password
eg. `-storepass "abcdef"`

but then in order to do that you have to change the password

my guess at first is because java may have decided to not allow those empty password anymore

but other scenarios could be failure of escaping empty string, or failure of discerning empty from null, eg. `<storepass></storepass>` (does that mean empty or null?)

side note a storepass is not the same as a keypass

anyway it seems by using a different storetype the bug does not occur, that said it does seem a Java bug and not an ADT bug

**Comment by gene-pavlovsky** [comment]
Why would I have to change the password, to try your suggestion? Like I mentioned from the beginner, the certificate is in fact protected by a (non-empty) password (and it's not even possible to set an empty password for an EV Code Signing certificate, at least using the tools from DigiCert).

I have just tried to do it per your suggestion `-storepass "actual password"`. This doesn't show any password prompts, and goes straight to the same exception as before.
I also tried removing the `-storepass` option altogether. This results in adt asking for a password in the terminal, and then it shows the same exception. The SafeNet GUI password prompt doesn't show up. If I recall correctly, the reason I added `-storepass ""` was to avoid the terminal prompt - same as I did now with the Windows-MY keystore type.

So far it seems to me like an ADT bug and not a Java bug, since `jarsigner` can sign .jar files without any issues. It could be a bug in Java, of course, caused by some peculiar way ADT is using. Either way, ADT is throwing an exception which is not being properly handled. Every item on the call stack trace is ADT's own code, not an internal Java exception. So if I was the programmer, I would assume I have to add some extra error handling and reporting, so that the user knows what exactly went wrong. Or report a bug in Java to Oracle, if I'm convinced it's their fault. Although even in that case I would add a workaround and/or a nice error message, since we can't expect external dependencies to fix (or even confirm) our bug reports in a timely manner.

**Comment by zwetan** [comment]
> Why would I have to change the password, to try your suggestion?

because the empty password is the problem, use of a non-empty password probably solve it
it feels just like an input parameter that is "not understood"


> Like I mentioned from the beginning, the certificate is in fact protected by a (non-empty) password

and you are confusing `storepass` vs `keypass`

you know what, I don't have time so good reading
https://stackoverflow.com/questions/5954459/keytools-storepass-vs-keypass-why-2-passwords

I didn't comment to end up on an argument, good luck

**Comment by gene-pavlovsky** [comment]
I'm sorry if it felt like I'm trying to make an argument. I appreciated your comments and trying to help, and I have faithfully tried every solution that you've suggested (e.g. an old Java 7 JDK, or omitting the `-storepass` option, or specifing the storepass on the command line). Unfortunately, none of these made any difference, which made me think this is not the issue here.

Now is the first time you mentioned the difference between storepass and keypass. But I don't quite understand what you're suggesting I should try. I understand that a keystore (e.g. Keychain on macOS, or a JKS file) can have a "master key", and then each individual certificate also having it's own key. But I'm not dealing with those kinds of keystores. The storetype in my case is PKCS11, with a SafeNet eToken USB device. The token has a single certificate installed into it, using a certificate installer tool provided by the CA (DigiCert). The token itself has a (token) password. The certificate itself doesn't seem to have an individual key. There is Safenet Authenticaiton Client Tools and DigiCertUtil which allow to do various things with the token. SAC Tools allows to change the token password. There is nothing about adding or changing a password for certificates themselves. To me it seems like the token has a store pass, and that there are no key pass in this case. Various experiments with keytool commands seem to confirm my suspicion.

If you have any particular suggestions regarding what exactly could I try, they are very welcome. Please provide more detail than before, as I'm not getting how can I achieve what you mention. Or even confirm that your theory is right.

**Comment by ajwfrost** [comment]
@gene-pavlovsky  Thanks for all the details - I'm glad you found a workaround, although I agree it might be better if ADL was able to cope with this. We're not able to see too much from the error that's thrown as the output you've shown is a re-throw based on the failure of the signing component, but we don't know what the failure was within that ..

Can I confirm then, that it fails with:
`-storetype PKCS11 -storepass "" -providerName SunPKCS11-eToken`
but succeeds with:
`-storetype Windows-MY -storepass "" -alias "Example Company LLC"`

We can look into this, are you able to send an email to adobe.support@harman.com about this issue and we can follow it up?

thanks

**Comment by gene-pavlovsky** [comment]
@ajwfrost Thanks, yes it looks like the error message is not very helpful for understanding what exactly is going wrong. Would be happy to assist in debugging/testing this.

Yes the Windows-MY command works and the SunPKCS11-eToken throws the exception.

E-mail sent!
