### ISSUE TITLE
Unable to build iOS ipa file with Air 33.1.1.217 in Flashbuilder 4.7

### ISSUE THREAD

**Issue by arminkapp** [Gamua/Adobe-Runtime-Support#480]
I am using Flashbuilder 4.7 on windows with Flex 4.16.1 and Air 33.1.1.217.
I believe I overlaid the Flex SDK with Air successfully, and I can run my application in the simulator.  The Harman splash screen briefly appears, and then my app starts up and runs without any errors in the simulator.

However, when I try to package a release build ipa file, I get the following error:

Error occurred while packaging the application:
java.lang.UnsupportedClassVersionError: com/adobe/air/ADT : Unsupported major.minor version 51.0

	at java.lang.ClassLoader.defineClass1(Native Method)

	at java.lang.ClassLoader.defineClassCond(Unknown Source)

	at java.lang.ClassLoader.defineClass(Unknown Source)

	at java.security.SecureClassLoader.defineClass(Unknown Source)

	at java.net.URLClassLoader.defineClass(Unknown Source)

	at java.net.URLClassLoader.access$000(Unknown Source)

	at java.net.URLClassLoader$1.run(Unknown Source)

	at java.security.AccessController.doPrivileged(Native Method)

	at java.net.URLClassLoader.findClass(Unknown Source)

	at java.lang.ClassLoader.loadClass(Unknown Source)

	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)

	at java.lang.ClassLoader.loadClass(Unknown Source)

Could not find the main class: com.adobe.air.ADT. Program will exit.

Exception in thread "main"

**Comment by ajwfrost** [comment]
This is an issue with the Java runtime. Due to the requirements from Google/Android, we had to use some features in a later version of Java than Flash Builder ships with (which I think is JRE6 aka 1.6..). Can you please try updating the 'jre' folder within Flash Builder, there should be some instructions (or links to instructions) within the SDK release notes? An earlier 1.8 version is usually a good one to try..

thanks

**Comment by arminkapp** [comment]
Andrew,
Thank you for pointing me in the right direction.  I have installed an earlier version of  Jave1.8, and got Flashbuilder running again (it did not work with the latest Java version).
I can once again run my project in the simulator.

However on exporting a release build I now get a new error:
SDK is missing file objects-13.0+.nib

Maybe you could once again point me in the right direction.

Thanks in advance!

**Comment by arminkapp** [comment]
Sorry, I did not mean to close this thread.

**Comment by ajwfrost** [comment]
Ah - this one is likely to be due to a change in Xcode 11 where the NIB format changed. A normal copy of the AIR SDK into an existing Flex/AIR SDK then fails because there is another NIB file that used to be a file, and is now a folder (containing that missing 'objects' one). So if you are able to look in your lib/aot/lib folder, you may see files called MainWindow.nib and MainWindow-ipad.nib. If you manually delete those, and then copy over the folders from the AIR SDK which have the same names, it should resolve it...

We're going to hit this again soon though, as Apple changed the format back again in Xcode 12...!

**Comment by arminkapp** [comment]
Andrew,
thank you again.  I replaced the two .nib files with the corresponding folders, and the compilation now starts and then after a couple of minutes stops with a new error:

Error occurred while packaging the application:
Id: entry point(start) undefined.  Usually in crt1.o for architecture arm64
Compilation failed while executing Id64

**Comment by xangel82** [comment]
Hello,
I follow your thread, I also have problems with build ipa, with FB4.7 and 33.1.1.217.
But the issue is a little bit different, after launch the packaging for apple ios, the adt.jar never end the build after hours.

In attach an extract of the threads. It seems the adt going to wating some things and never close the build.

M. 
[Campione di ADT.txt](https://github.com/Gamua/Adobe-Runtime-Support/files/5310908/Campione.di.ADT.txt)

**Comment by Marcophono2** [comment]
Just 2 cents from me related to the (early) 1.8 Java/JDK version. I can recommend version 1.8.0_211. With later versions of 1.8 you may struggle with existing certificates build on older Java versions. May be this is restricted to Android, not sure right now and you also did not say that you have trouble with your certificates but may be others may find this thread later. 

Best regards
Marc

**Comment by xangel82** [comment]
Hi Marc, I use 1.8.0_101 for bypass the certificate issue, however with android no problem for build and submit the application on PlayConsole.

The issue is for  build IPA (Apple), I tried different workaround, but when i launch the packaging of the application, it never ends. 

ADT launch the compilation abcx64 but when it's end ADT going in standby and don't close the build.

**Comment by iancucatalin1993** [comment]
@ajwfrost @xangel82 Thank you all, it works. I would have never managed without your suggestions.

**Comment by xangel82** [comment]
Hi, 
I updated the harman to 33.1.1.345, but when i try to build IPA I have the some issue, ADT launch the compilation abcx64 but when it's end ADT going in pending/standby and don't close the build.

Untill ADT is in pending the "Export Relase Build" view don't will be closed .

Some one can help me? Or suggest a workaround?

Thanks a lot

**Comment by xangel82** [comment]
I found the issue the problem was an library (to old) in my workspace, but the ADT inside the FB 4.7 never give me information about the error.

I found the issue with Intellij Idea :(

However i builded an IPA with Herman 33.1.1.345.

**Comment by Shaunmax** [comment]
can someone tell me how to solve this issue, I am facing a similar issue after migrating the project to a new mac

Exception in thread "main" 
java.lang.IllegalAccessError: class com.adobe.air.ipa.MachoSigner (in unnamed module @0x11739fa6) cannot access class sun.security.x509.X500Name (in module java.base) because module java.base does not export sun.security.x509 to unnamed module @0x11739fa6
	at com.adobe.air.ipa.MachoSigner.isDistributionCert(MachoSigner.java)
	at com.adobe.air.ipa.IPASigner.isDistributionCert(IPASigner.java)
	at com.adobe.air.ipa.IPAOutputStream.createNewEntitlementPlist(IPAOutputStream.java)
	at com.adobe.air.ipa.IPAOutputStream.finalizeSig(IPAOutputStream.java)
	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
	at com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)
	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
	at com.adobe.air.ADT.run(ADT.java)
	at com.adobe.air.ADT.main(ADT.java)
