### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference com.adobe.air.AndroidActivityWrapper.embeddedFonts

### ISSUE THREAD

**Issue by leossmith** [Gamua/Adobe-Runtime-Support#507]
## Problem Description

A few days ago, I upgraded one of our apps to the latest x.259 version of the sdk and now I am getting increased reports of the following error:

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
com.adobe.air.AndroidActivityWrapper.embeddedFonts

This looks like mostly affecting Android 10

## Logs

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
       at com.adobe.air.AndroidActivityWrapper.embeddedFonts(AndroidActivityWrapper.java:460)
       at com.adobe.air.AndroidStageText.<init>(AndroidStageText.java:616)
       at com.adobe.air.customHandler.callTimeoutFunction(customHandler.java)
       at com.adobe.air.customHandler.handleMessage(customHandler.java:22)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7617)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

```

**Comment by ajwfrost** [comment]
Thanks for the report; we're seeing increasing numbers of this sort of thing, where there are assumptions in the Activity about the presence of the view etc; it seems like the async callbacks (Looper -> dispatchMessage) are continuing on even when the activity has been closed. We've suspected a subtle change in how Android is doing the lifecycle management so have been putting code in to try to handle this sort of case. There are some updates that should come in to our forthcoming release but if you see any others, these sorts of call stacks are very useful!

thanks

**Comment by leossmith** [comment]
Right now it doesnt affect many users as you can see in the screenshot bellow, but definately something that should be fixed. 

![image](https://user-images.githubusercontent.com/4300876/97281160-d927b400-1845-11eb-9294-76df8725881a.png)
