### ISSUE TITLE
AIR Apps not running on Samsung Galaxy Tab devices

### ISSUE THREAD

**Issue by eliahw** [Gamua/Adobe-Runtime-Support#652]
This is a new issue in reference to #525 as it got crowded with similar issues that seem to be fixed by the current AIR SDK 33.1.1.345.

## Problem Description

Android apps built with AIR SDK 33 via FlashDevelop crash on Samsung Galaxy Tab devices with the following error logs:

```
avc:  denied  { execmod } for  pid=4848 comm="estAppAS3Mobile" path="/data/app/air.air.de.sinus.test.TestAppAS3Mobile-4Hc_qTwe3ljp2hCN2H8TQQ==/lib/arm/libCore.so" dev="mmcblk0p33" ino=1376543 scontext=u:r:untrusted_app:s0:c4,c256,c512,c768 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0 SEPF_SM-T510_10_0020 audit_filtered
arch=40000028 syscall=125 per=8 success=no exit=-13 a0=c4373000 a1=1000 a2=5 a3=0 items=0 ppid=3547 pid=4848 auid=4294967295 uid=10004 gid=10004 euid=10004 suid=10004 fsuid=10004 egid=10004 sgid=10004 fsgid=10004 tty=(none) ses=4294967295 comm="estAppAS3Mobile" exe="/system/bin/app_process32" subj=u:r:untrusted_app:s0:c4,c256,c512,c768 key=(null)
proctitle="air.air.de.sinus.test.TestAppAS3Mobile"

    --------- beginning of crash
Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xc4373000 in tid 4848 (estAppAS3Mobile), pid 4848 (estAppAS3Mobile)
pid: 4848, tid: 4848, name: estAppAS3Mobile  >>> air.air.de.sinus.test.TestAppAS3Mobile <<<
      #00 pc 00ceb000  /data/app/air.air.de.sinus.test.TestAppAS3Mobile-4Hc_qTwe3ljp2hCN2H8TQQ==/lib/arm/libCore.so!libCore.so (offset 0xce7000) (BuildId: ca591d11ca1f5800fa560b863774bca9a69742cc)
auid=4294967295 uid=10004 gid=10004 ses=4294967295 subj=u:r:untrusted_app:s0:c4,c256,c512,c768 pid=4848 comm="estAppAS3Mobile" exe="/system/bin/app_process32" sig=11

RemoteException occurs on reporting focusChanged, w=Window{27ec0f4 u0 air.air.de.sinus.test.TestAppAS3Mobile/air.air.de.sinus.test.TestAppAS3Mobile.AppEntry}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:575)
        at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:829)
        at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3691)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5254)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

The app works without a problem on other devices.

## Steps to Reproduce

Create a new AS3 Mobile App in FlashDevelop.
No external libraries, ANEs or any additional code in `Main.as`.

We tried the following software versions:

**Architecture:**

* 32bit and 64bit builds by editing `adt.cfg`

**AIR SDK (Flex Windows):**

* 33.0.2.338
* 33.1.1.300
* 33.1.1.345

**Android SDK:**

* 21
* 26
* 28

**Java JDK:**

* 8u271
* 8u261
* 7u80

**Android (on SM-T510)**:

* Android 10
* Android 9

**Flex SDK:**

* 4.6.0

**FlashDevelop:**

* 5.3.3.1

<hr />

Please let us know if there is anything else we can try or if you need more information.
We'd be happy if we can help trying to fix this issue by trying new AIR SDK versions.

**Comment by eliahw** [comment]
Edit: added 33.1.1.406

Tried with this version aswell

**Comment by denweng** [comment]
Was someone able to built and run app on Glaxy Tab 10 / Android, with one of the mentioned versions or later versions?

**Comment by ajwfrost** [comment]
We'd verified it works on:
```
Name: Samsung Galaxy Tab S6 (WiFi)
OS: 9
```
using the latest SDK (well actually, with the forthcoming SDK, using targetSdkVersion=30).
The error report mentions it's "untrusted", but I'm assuming this is a signed APK file?

**Comment by ajwfrost** [comment]
Just to add ... if you have an APK that's got this issue - especially if you can build it with "apk-debug" - then please send it to us for inspection. I would have said that versions before 33.1.1.217 would have this execmod issue, but anything from then on should not be trying to modify the executable...
