### ISSUE TITLE
AAPT Error in AIR SDK 33.1 with build tools 29.0.3/30.0.3 (null returned: -1073741515)

### ISSUE THREAD

**Issue by Tiuser4567** [Gamua/Adobe-Runtime-Support#660]
## Problem Description

Hello, problem building the Android APK using AIR SDK 33 using ADT.
* AIR SDK 33
* Android Target API 29
* Windows Server 2008 R2

Error "null returned: -1073741515" for the aapt command is being thrown. I tried verbose and debug but no underlying exception is being thrown.

Partial stacktrace below:
```
    [echo] ----------
     [echo] Handling Resources...
     [aapt] Found Deleted Target File
     [aapt]
     [aapt] Generating resource IDs...
     [aapt]
Class org.apache.tools.ant.types.Commandline$Argument loaded from parent loader
(parentFirst)
     [aapt] Current OS is Windows Server 2008 R2
     [aapt] Executing 'C:\Progs\adt_20131030\sdk\build-tools\30.0.3\aapt.exe' wi
th arguments:
     [aapt] 'package'
     [aapt] '--non-constant-id'
     [aapt] '-f'
     [aapt] '-v'
     [aapt] '-m'
     [aapt] '-0'
     [aapt] 'apk'
     [aapt] '--output-text-symbols'
     [aapt] 'C:\mmis\MMISViewerAppAndroid\bin'
     [aapt] '-M'
     [aapt] 'C:\mmis\MMISViewerAppAndroid\bin\AndroidManifest.xml'
     [aapt] '-S'
     [aapt] 'C:\mmis\MMISViewerAppAndroid\bin\res'
     [aapt] '-S'
     [aapt] 'C:\mmis\MMISViewerAppAndroid\res'
     [aapt] '-I'
     [aapt] 'C:\Progs\adt_20131030\sdk\platforms\android-29\android.jar'
     [aapt] '-J'
     [aapt] 'C:\mmis\MMISViewerAppAndroid\gen'
     [aapt] '--generate-dependencies'
     [aapt] '-G'
     [aapt] 'C:\mmis\MMISViewerAppAndroid\bin\proguard.txt'
     [aapt]
     [aapt] The ' characters around the executable and arguments are
     [aapt] not part of the command.
Execute:Java13CommandLauncher: Executing 'C:\Progs\adt_20131030\sdk\build-tools\
30.0.3\aapt.exe' with arguments:
'package'
'--non-constant-id'
'-f'
'-v'
'-m'
'-0'
'apk'
'--output-text-symbols'
'C:\mmis\MMISViewerAppAndroid\bin'
'-M'
'C:\mmis\MMISViewerAppAndroid\bin\AndroidManifest.xml'
'-S'
'C:\mmis\MMISViewerAppAndroid\bin\res'
'-S'
'C:\mmis\MMISViewerAppAndroid\res'
'-I'
'C:\Progs\adt_20131030\sdk\platforms\android-29\android.jar'
'-J'
'C:\mmis\MMISViewerAppAndroid\gen'
'--generate-dependencies'
'-G'
'C:\mmis\MMISViewerAppAndroid\bin\proguard.txt'

The ' characters around the executable and arguments are
not part of the command.
  [antcall] Exiting C:\mmis\MMISViewerAppAndroid\build.xml.
      [ant] Exiting C:\mmis\MMISViewerAppAndroid\build.xml.

BUILD FAILED
C:\mmis\AndroidANECompiler\build.xml:62: The following error occurred while exec
uting this line:
C:\mmis\MMISViewerAppAndroid\build.xml:95: The following error occurred while ex
ecuting this line:
C:\Progs\adt_20131030\sdk\tools\ant\build.xml:649: The following error occurred
while executing this line:
C:\Progs\adt_20131030\sdk\tools\ant\build.xml:694: null returned: -1073741515
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:644)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:670)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
        at com.android.ant.AaptExecTask.execute(AaptExecTask.java:703)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav
a:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav
a:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav
a:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.jav
a:396)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav
a:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(Single
CheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)

        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav
a:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(Single
CheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav
a:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExe
cutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:853)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

Total time: 3 seconds
```

Please help advise how to resolve or further investigate the issue.

One thing to note is that in another machine (Windows 7, dev machine), the error is not thrown. 
Same java version, ant version, same AIR SDK 33 and same android SDK tool files are used.

Note that AIR SDK 32 is working. the only change applied to use AIR SDK 33 (for 64bit) and change target api to 29 (google play requirement) in the AndroidManifest.xml (no changes in strings.xml etc).

**Comment by Tiuser4567** [comment]
Sorry, found that running the aapt command results to some dll missing (related to Visual C++ Redistributable). The Windows 7 machine had several of these but the build server did not. Will close this issue.
