### ISSUE TITLE
iOS with AIR 33: VerifyError: Error #1014: Class flash.display::Stage3D could not be found

### ISSUE THREAD

**Issue by tuarua** [Gamua/Adobe-Runtime-Support#74]
## Problem Description

Describe your problem in detail. Include the following information:

When building a bare minimum AIR app with Stage3D the base classes are not found and fdb throws VerifyErrors. Problem is seen with any Starling based app.

[trace] typecheck Main()
[trace]   outer-scope = [global Object$ flash.events::EventDispatcher$ flash.display::DisplayObject$ flash.display::InteractiveObject$ flash.display::DisplayObjectContainer$ flash.display::Sprite$ Main$]
[trace]                        [Main~ *] {} ()
[trace]   0:getlocal0
[trace]                        [Main~ *] {} (Main~)
[trace]   1:pushscope
[trace]                        [Main~ *] {Main~} ()
[trace]   2:debugfile "/Users/eoinlandy/flash/TestIOS33/src;;Main.as"
[trace]                        [Main~ *] {Main~} ()
[trace]   4:debug
[trace]                        [Main~ *] {Main~} ()
[trace]   9:getlocal0
[trace]                        [Main~ *] {Main~} (Main~)
[trace]   10:constructsuper 0
[trace]                        [Main~ *] {Main~} ()
[trace]   12:getlex 4
[trace]                        [Main~ *] {Main~} (flash.display::Stage)
[trace]   14:debugline 12
[trace]                        [Main~ *] {Main~} (flash.display::Stage)
[trace]   16:getproperty stage3Ds
[trace]                        [Main~ *] {Main~} (*)
[trace]   18:coerce __AS3__.vec::Vector
[Fault] exception, information=VerifyError: Error #1014: Class flash.display::Stage3D could not be found.
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at flash.tools.debugger.concrete.DManager.getFrame(DManager.java:921)
	at flash.tools.debugger.concrete.PlayerSession.pullUpActivationObjectVariables(PlayerSession.java:1113)
	at flash.tools.debugger.concrete.PlayerSession.requestFrame(PlayerSession.java:1089)
	at flash.tools.debugger.concrete.PlayerSession.getValueWorker(PlayerSession.java:1211)
	at flash.tools.debugger.concrete.IsolatePlayerSession.getValue(IsolatePlayerSession.java:123)
	at flex.tools.debugger.cli.ExpressionContext.memberNamed(ExpressionContext.java:438)
	at flex.tools.debugger.cli.ExpressionContext.locateParentForNamed(ExpressionContext.java:540)
	at flex.tools.debugger.cli.ExpressionContext.determineContext(ExpressionContext.java:490)
	at flex.tools.debugger.cli.ExpressionContext.resolveToVariable(ExpressionContext.java:350)
	at flex.tools.debugger.cli.ExpressionContext.lookup(ExpressionContext.java:169)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:161)
	at macromedia.asc.parser.ThisExpressionNode.evaluate(ThisExpressionNode.java:34)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:1031)
	at macromedia.asc.parser.ListNode.evaluate(ListNode.java:44)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:1031)
	at macromedia.asc.parser.ListNode.evaluate(ListNode.java:44)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:1065)
	at macromedia.asc.parser.ExpressionStatementNode.evaluate(ExpressionStatementNode.java:50)
	at flash.tools.debugger.expression.DebuggerEvaluator.evaluate(DebuggerEvaluator.java:1306)
	at macromedia.asc.parser.ProgramNode.evaluate(ProgramNode.java:80)
	at flash.tools.debugger.expression.DebuggerExpression.evaluate(DebuggerExpression.java:106)
	at flex.tools.debugger.cli.ExpressionCache.evaluate(ExpressionCache.java:101)
	at flex.tools.debugger.cli.DebugCLI.evalExpression(DebugCLI.java:4023)
	at flex.tools.debugger.cli.DebugCLI.evalExpression(DebugCLI.java:4015)
	at flex.tools.debugger.cli.DebugCLI.doPrint(DebugCLI.java:3941)
	at flex.tools.debugger.cli.DebugCLI.processLine(DebugCLI.java:7032)
	at flex.tools.debugger.cli.DebugCLI.process(DebugCLI.java:828)
	at flex.tools.debugger.cli.DebugCLI.execute(DebugCLI.java:669)
	at flex.tools.debugger.cli.DebugCLI.main(DebugCLI.java:461)

* Which AIR SDK did you use?
33.0.0.212 on macOS 10.14.6
* Describe the affected environment: 
AIR iOS app debugged on both iOS device with 11.4 and Simulator 11.1
* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
Yes 100%

## Steps to Reproduce

1. Create an iOS AIR app with the following:
```xml
//Main.xml
<application xmlns="http://ns.adobe.com/air/application/33.0">
<id>Main</id>
<filename>Main</filename>
<name>Main</name>
<initialWindow>
        <content>[This value will be overwritten by Flash Builder in the output app.xml]</content>
        <aspectRatio>portrait</aspectRatio>
        <autoOrients>false</autoOrients>
        <fullScreen>true</fullScreen>
        <renderMode>direct</renderMode>
        <depthAndStencil>true</depthAndStencil>
        <visible>true</visible>
    </initialWindow>
</application>
```

```actionscript
// Main.as
package {

import flash.display.Sprite;
import flash.display.Stage3D;
import flash.display3D.Context3D;
import flash.events.Event;


[SWF(width="320", height="480", frameRate="60", backgroundColor="#FFFFFF")]
public class Main extends Sprite {

    public function Main() {
        var stage3Ds:Vector.<Stage3D> = stage.stage3Ds;
        trace("stage3Ds.length", stage3Ds.length);
        if (stage3Ds.length > 0) {
            stage3Ds[0].addEventListener(Event.CONTEXT3D_CREATE, initStage3D);
            stage3Ds[0].requestContext3D();
        }

    }

    protected function initStage3D(e:Event):void {
        var context3D:Context3D = stage.stage3Ds[0].context3D;
    }
}
}
```

## Known Workarounds

Target AIR 32 instead

**Comment by hcsuk** [comment]
Namespace 33.0 isn't valid I'm afraid. For some reason rather than saying "namespace not valid", it's throwing VerifyErrors. Please switch to 32.0 and it should then all work...

thanks
