### ISSUE TITLE
Android application crashed/stops if there is no internet connection

### ISSUE THREAD

**Issue by Oldes** [Gamua/Adobe-Runtime-Support#90]
## Problem Description

There seems to be integrated license check in the Herman's version, but if there is no connection, it crashes with error:

```
08-26 16:24:34.598 24409-24426/? D/AppEntry: failed to connect to /3.16.218.255 (port 80): connect failed: ETIMEDOUT (Connection timed out)
08-26 16:24:34.608 24409-24409/? D/AppEntry: Licence Response  :null
08-26 16:24:34.608 24409-24409/? D/AndroidRuntime: Shutting down VM
08-26 16:24:34.608 24409-24409/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: air.com.foo.VideoTest, PID: 24409
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
        at org.json.JSONTokener.nextValue(JSONTokener.java:94)
        at org.json.JSONObject.<init>(JSONObject.java:156)
        at org.json.JSONObject.<init>(JSONObject.java:173)
        at air.com.foo.VideoTest.AppEntry$LicenceServiceAsyncTask.onPostExecute(AppEntry.java:1484)
        at air.com.foo.VideoTest.AppEntry$LicenceServiceAsyncTask.onPostExecute(AppEntry.java:1435)
        at android.os.AsyncTask.finish(AsyncTask.java:636)
        at android.os.AsyncTask.access$500(AsyncTask.java:177)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:7007)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

* Which AIR SDK did you use?

AIR 33.0.0.212

**Comment by ajwfrost** [comment]
Hi - yes that particular build included the beginnings of a ping-back service so that we could track the deployments of the AIR binaries, but this has since been removed. So this issue won't be found with the proper release of AIR 33..

thanks

**Comment by ajwfrost** [comment]
Fixed in 33.0.1.x and later as we no longer have any pingbacks in the core library.. closing this now to tidy up..
